CREATE TABLE IF NOT EXISTS public.client
(
    id            BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name    varchar(255) NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    price         DECIMAL NOT NULL,
    PRIMARY KEY (id)
);