server:
  port: 9292
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@activatedProperties@'
  datasource:
    url: jdbc:postgresql://localhost:5432/client_db?useSSL=false&useFractionalSeconds=true
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none #en prod validate
      show-sql: false #en prod false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      properties:
        hibernate:
          cache:
            use_query_cache: false
            use_second_level_cache: false

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: beta
  datasource:
    url: jdbc:postgresql://postgres:5432/client_db?useSSL=false&useFractionalSeconds=true

server:
  port: 9292
  servlet:
    context-path: /client